version: '3.8'

services:
  postgres_test:
    image: postgres:15
    container_name: server_discovery_test_db
    environment:
      POSTGRES_DB: server_discovery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Using 5433 to avoid conflicts with local PostgreSQL if installed
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 