apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server-discovery.fullname" . }}
  labels:
    {{- include "server-discovery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "server-discovery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "server-discovery.selectorLabels" . | nindent 8 }}
    spec:
      shareProcessNamespace: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "server-discovery.fullname" . }}-config
        - name: output-volume
          emptyDir: {}
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.apiServer.port }}
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /app
            - name: output-volume
              mountPath: /tmp/server-discovery
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/stats
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/stats
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5 